# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: WePay Developer Docs
email: api@wepay.com
description: > # this means to ignore newlines until "baseurl:"
  WePay Developer Documentation. Designed for platforms like marketplaces,
  crowdfunding sites & small business tools. Get a seamless user
  experience & fraud protection.

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: "/api-team/developer-docs" # the subpath of your site, e.g. /blog
url: "https://pages.github.devops.wepay-inc.com" # the base hostname & protocol for your site
twitter_username: wepay
github_username:  wepay
wepay_font_path: /fonts/NoyhRegular
wepay_nav_font_path: /fonts/NoyhBookRegular
wepay_logo_bw: /images/bwlogo.svg
wepay_developers_logo: "/images/wepay-dev-logo-2x.png"
wepay_favicon: "/images/favicon.png"
navigation:
- text: "Overview"
  url: "/"
  pages:
  - text: "Introduction"
    url: "/"
  - text: "Payment Methods"
    url: "/"
- text: "Integrating with WePay"
  url: "/integration/onboarding/"
  pages:
  - text: "Onboarding Your Merchants"
    url: "/integration/onboarding/"
    pages:
    - text: "Sub page 1"
      url: "/integration/onboarding/"
      pages:
      - text: "Longer title test yolo swag some api/call"
        url: "/integration/onboarding/"
      - text: "Sub sub page 2"
        url: "/integration/onboarding/"
      - text: "Sub sub page 3"
        url: "/integration/onboarding/"
    - text: "Sub page 2"
      url: "/integration/onboarding/"
    - text: "Sub page 3"
      url: "/integration/onboarding/"
- text: "Implementation Options"
  url: "/"
  pages:
  - text: "2-step Security"
    url: "/implementation/mfa/"
  - text: "Single Sign On (SSO)"
    url: "/implementation/sso"
- text: "Enhanced Features"
  url: "/"
  pages:
  - text: "Mobile Point of Sale"
    url: "/"
- text: "Developer Guides"
  url: "/"
  pages:
  - text: "Integration Basics"
    url: "/"
  - text: "Access Tokens"
    url: "/guides/access-tokens"
  - text: "Account ID"
    url: "/reference/account-id"
  - text: "Analytics"
    url: "/guides/analytics"
  - text: "Customization and Themes"
    url: "/guides/customization"
  - text: "Instant Payment Notifications (IPN)"
    url: "/guides/ipn"
  - text: "Throttling"
    url: "/reference/throttling"
  - text: "Versioning APIs"
    url: "/reference/versioning"
- text: "General"
  url: "/"
  pages:
  - text: "Certification"
    url: "/"
  - text: "Developer FAQs"
    url: "/"
  - text: "Error Codes"
    url: "/reference/errors"
  - text: "Making API Calls"
    url: "/general/api-call"
  - text: "Merchant Category Codes - U.S."
    url: "/reference/mcc"
  - text: "Merchant Category Codes - U.K."
    url: "/reference/uk_mcc_codes"
  - text: "Permisions"
    url: "/reference/permissions"
  - text: "rbit Types"
    url: "/reference/rbit_types"
  - text: "Structures"
    url: "/reference/structures"
- text: "API Reference"
  url: "/"
  external: true
  pages:
    - text: "Account"
      url: "/api-calls/account/"
    - text: "Account Membership"
      url: "/api-calls/account-membership"
    - text: "Batch"
      url: "/api-calls/batch"
    - text: "Checkout"
      url: "/api-calls/checkout"
    - text: "Credit Card"
      url: "/api-calls/credit_card/"
    - text: "Know Your Customer (KYC)"
      url: "/api-calls/kyc"
    - text: "OAuth 2"
      url: "/api-calls/oauth2"
    - text: "Payment Bank"
      url: "/api-calls/payment_bank"
    - text: "Preapproval"
      url: "/api-calls/preapproval"
    - text: "rbit API"
      url: "/api-calls/rbit"
    - text: "Reports"
      url: "/api-calls/reports"
    - text: "Settlement"
      url: "/api-calls/settlement"
    - text: "User"
      url: "/api-calls/user/"
    - text: "User MFA"
      url: "/api-calls/user-mfa/"
    - text: "Withdrawal"
      url: "/api-calls/withdrawal"






# Build settings
markdown: kramdown

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-gist # Show a gist


include: ['_pages']

repository: api-team/developer-docs

sass:
    style: :compressed
