# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sean McIntyre's GitHub
email: sean@seansworld.com
description: > # this means to ignore newlines until "baseurl:" This is the place where you can find samples of my work.

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#baseurl: "/api-team/developer-docs" # the subpath of your site, e.g. /blog
url: "https://seanmc2.github.io" # the base hostname & protocol for your site
github_username:  seanmc2
# wepay_font_path: /fonts/NoyhRegular
# wepay_nav_font_path: /fonts/NoyhBookRegular
# wepay_logo_bw: /images/bwlogo.svg
# wepay_developers_logo: "/images/wepay-dev-logo-2x.png"
# wepay_favicon: "/images/favicon.png"
# navigation:


# Build settings
markdown: kramdown

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-gist # Show a gist


include: ['_pages']

repository: seanmc2.github.io

sass:
    style: :compressed
